package oracle.tms.offencemanager.model.appmodule.client;

import oracle.jbo.client.remote.ApplicationModuleImpl;

import oracle.jbo.domain.Number;

import oracle.tms.offencemanager.model.appmodule.common.BrowseOffenceAM;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Jul 27 11:43:42 IST 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class BrowseOffenceAMClient extends ApplicationModuleImpl implements BrowseOffenceAM {
    /**
     * This is the default constructor (do not remove).
     */
    public BrowseOffenceAMClient() {
    }

    public void getOffenceDetails(Number key) {
        Object _ret =
            this.riInvokeExportedMethod(this,"getOffenceDetails",new String [] {"oracle.jbo.domain.Number"},new Object[] {key});
        return;
    }
}
