package oracle.tms.offencemanager.model.appmodule.client;

import oracle.jbo.client.remote.ApplicationModuleImpl;

import oracle.jbo.domain.DBSequence;
import oracle.jbo.domain.Number;

import oracle.tms.offencemanager.model.appmodule.common.TrafficManagerAM;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Jul 24 11:59:41 IST 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class TrafficManagerAMClient extends ApplicationModuleImpl implements TrafficManagerAM {
    /**
     * This is the default constructor (do not remove).
     */
    public TrafficManagerAMClient() {
    }


    public void searchPendingOffences(String status) {
        Object _ret =
            this.riInvokeExportedMethod(this,"searchPendingOffences",new String [] {"java.lang.String"},new Object[] {status});
        return;
    }

    public void calculateTotal() {
        Object _ret = this.riInvokeExportedMethod(this,"calculateTotal",null,null);
        return;
    }

    public void onDeleteOffence(DBSequence key) {
        Object _ret =
            this.riInvokeExportedMethod(this,"onDeleteOffence",new String [] {"oracle.jbo.domain.DBSequence"},new Object[] {key});
        return;
    }
}
