package oracle.tms.offencemanager.model.uiview;

import oracle.jbo.domain.Number;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Jul 24 11:24:55 IST 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class OffenceDetailJoinedVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public OffenceDetailJoinedVOImpl() {
    }

    /**
     * Returns the variable value for Offence_Detail_Id.
     * @return variable value for Offence_Detail_Id
     */
    public Number getOffence_Detail_Id() {
        return (Number)ensureVariableManager().getVariableValue("Offence_Detail_Id");
    }

    /**
     * Sets <code>value</code> for variable Offence_Detail_Id.
     * @param value value to bind as Offence_Detail_Id
     */
    public void setOffence_Detail_Id(Number value) {
        ensureVariableManager().setVariableValue("Offence_Detail_Id", value);
    }

    /**
     * Returns the variable value for Vehicle_Number.
     * @return variable value for Vehicle_Number
     */
    public String getVehicle_Number() {
        return (String)ensureVariableManager().getVariableValue("Vehicle_Number");
    }

    /**
     * Sets <code>value</code> for variable Vehicle_Number.
     * @param value value to bind as Vehicle_Number
     */
    public void setVehicle_Number(String value) {
        ensureVariableManager().setVariableValue("Vehicle_Number", value);
    }

    /**
     * Returns the variable value for Offence_Status.
     * @return variable value for Offence_Status
     */
    public String getOffence_Status() {
        return (String)ensureVariableManager().getVariableValue("Offence_Status");
    }

    /**
     * Sets <code>value</code> for variable Offence_Status.
     * @param value value to bind as Offence_Status
     */
    public void setOffence_Status(String value) {
        ensureVariableManager().setVariableValue("Offence_Status", value);
    }
}
