package oracle.tms.offencemanager.model.uiview;

import oracle.jbo.server.ViewDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Jul 15 16:58:58 IST 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class TmOffenceDetailsVODefImpl extends ViewDefImpl {
    public TmOffenceDetailsVODefImpl(String name) {
        super(name);
    }

    /**
     * This is the default constructor (do not remove).
     */
    public TmOffenceDetailsVODefImpl() {
    }
}
