package oracle.tms.offencemanager.model.appmodule.common;

import oracle.jbo.ApplicationModule;
import oracle.jbo.domain.Number;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Jul 27 11:43:42 IST 2015
// ---------------------------------------------------------------------
public interface BrowseOffenceAM extends ApplicationModule {
    void getOffenceDetails(Number key);
}
