package oracle.tms.offencemanager.model.appmodule.common;

import oracle.jbo.ApplicationModule;
import oracle.jbo.domain.DBSequence;
import oracle.jbo.domain.Number;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Jul 24 11:59:41 IST 2015
// ---------------------------------------------------------------------
public interface TrafficManagerAM extends ApplicationModule {
    void searchPendingOffences(String status);

    void calculateTotal();

    void onDeleteOffence(DBSequence key);
}
