package oracle.tms.offencemanager.model.entity;

import oracle.jbo.server.EntityCache;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Jul 22 21:12:48 IST 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class TmOwnerdetailsEOCollImpl extends EntityCache {
    /**
     * This is the default constructor (do not remove).
     */
    public TmOwnerdetailsEOCollImpl() {
    }
}
