package oracle.tms.offencemanager.model.entity;

import java.text.DateFormat;

import java.text.SimpleDateFormat;

import oracle.jbo.Key;
import oracle.jbo.RowIterator;
import oracle.jbo.RowSet;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.SequenceImpl;

import oracle.tms.offencemanager.model.domain.common.Telephone;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Jul 22 21:12:48 IST 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class TmOwnerdetailsEOImpl extends EntityImpl {
    private static EntityDefImpl mDefinitionObject;

    @Override
    protected void initDefaults() {
        super.initDefaults();
      SequenceImpl seq = new SequenceImpl("TM_OWNER_ID_SEQ",
      getDBTransaction());
      populateAttributeAsChanged(OWNERID,
      seq.getSequenceNumber());
    }

    /**
     * Validation method for Dateofbirth.
     */
    public boolean validateDateofbirth(Date dateofbirth) {    
      Date today = new Date();        
      return dateofbirth.compareTo(today) >  0 ;
    }
 
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        OwnerId {
            public Object get(TmOwnerdetailsEOImpl obj) {
                return obj.getOwnerId();
            }

            public void put(TmOwnerdetailsEOImpl obj, Object value) {
                obj.setOwnerId((Number)value);
            }
        }
        ,
        Fname {
            public Object get(TmOwnerdetailsEOImpl obj) {
                return obj.getFname();
            }

            public void put(TmOwnerdetailsEOImpl obj, Object value) {
                obj.setFname((String)value);
            }
        }
        ,
        Lname {
            public Object get(TmOwnerdetailsEOImpl obj) {
                return obj.getLname();
            }

            public void put(TmOwnerdetailsEOImpl obj, Object value) {
                obj.setLname((String)value);
            }
        }
        ,
        Dateofbirth {
            public Object get(TmOwnerdetailsEOImpl obj) {
                return obj.getDateofbirth();
            }

            public void put(TmOwnerdetailsEOImpl obj, Object value) {
                obj.setDateofbirth((Date)value);
            }
        }
        ,
        LandlineNo {
            public Object get(TmOwnerdetailsEOImpl obj) {
                return obj.getLandlineNo();
            }

            public void put(TmOwnerdetailsEOImpl obj, Object value) {
                obj.setLandlineNo((String)value);
            }
        }
        ,
        MobileNo {
            public Object get(TmOwnerdetailsEOImpl obj) {
                return obj.getMobileNo();
            }

            public void put(TmOwnerdetailsEOImpl obj, Object value) {
                obj.setMobileNo((String)value);
            }
        }
        ,
        Gender {
            public Object get(TmOwnerdetailsEOImpl obj) {
                return obj.getGender();
            }

            public void put(TmOwnerdetailsEOImpl obj, Object value) {
                obj.setGender((String)value);
            }
        }
        ,
        TempAddr {
            public Object get(TmOwnerdetailsEOImpl obj) {
                return obj.getTempAddr();
            }

            public void put(TmOwnerdetailsEOImpl obj, Object value) {
                obj.setTempAddr((String)value);
            }
        }
        ,
        PermAddr {
            public Object get(TmOwnerdetailsEOImpl obj) {
                return obj.getPermAddr();
            }

            public void put(TmOwnerdetailsEOImpl obj, Object value) {
                obj.setPermAddr((String)value);
            }
        }
        ,
        Pincode {
            public Object get(TmOwnerdetailsEOImpl obj) {
                return obj.getPincode();
            }

            public void put(TmOwnerdetailsEOImpl obj, Object value) {
                obj.setPincode((Number)value);
            }
        }
        ,
        Occupation {
            public Object get(TmOwnerdetailsEOImpl obj) {
                return obj.getOccupation();
            }

            public void put(TmOwnerdetailsEOImpl obj, Object value) {
                obj.setOccupation((String)value);
            }
        }
        ,
        PancardNo {
            public Object get(TmOwnerdetailsEOImpl obj) {
                return obj.getPancardNo();
            }

            public void put(TmOwnerdetailsEOImpl obj, Object value) {
                obj.setPancardNo((String)value);
            }
        }
        ,
        AddProofName {
            public Object get(TmOwnerdetailsEOImpl obj) {
                return obj.getAddProofName();
            }

            public void put(TmOwnerdetailsEOImpl obj, Object value) {
                obj.setAddProofName((String)value);
            }
        }
        ,
        TmVehicledetails {
            public Object get(TmOwnerdetailsEOImpl obj) {
                return obj.getTmVehicledetails();
            }

            public void put(TmOwnerdetailsEOImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        TmOffenceVVO1 {
            public Object get(TmOwnerdetailsEOImpl obj) {
                return obj.getTmOffenceVVO1();
            }

            public void put(TmOwnerdetailsEOImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(TmOwnerdetailsEOImpl object);

        public abstract void put(TmOwnerdetailsEOImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int OWNERID = AttributesEnum.OwnerId.index();
    public static final int FNAME = AttributesEnum.Fname.index();
    public static final int LNAME = AttributesEnum.Lname.index();
    public static final int DATEOFBIRTH = AttributesEnum.Dateofbirth.index();
    public static final int LANDLINENO = AttributesEnum.LandlineNo.index();
    public static final int MOBILENO = AttributesEnum.MobileNo.index();
    public static final int GENDER = AttributesEnum.Gender.index();
    public static final int TEMPADDR = AttributesEnum.TempAddr.index();
    public static final int PERMADDR = AttributesEnum.PermAddr.index();
    public static final int PINCODE = AttributesEnum.Pincode.index();
    public static final int OCCUPATION = AttributesEnum.Occupation.index();
    public static final int PANCARDNO = AttributesEnum.PancardNo.index();
    public static final int ADDPROOFNAME = AttributesEnum.AddProofName.index();
    public static final int TMVEHICLEDETAILS = AttributesEnum.TmVehicledetails.index();
    public static final int TMOFFENCEVVO1 = AttributesEnum.TmOffenceVVO1.index();

    /**
     * This is the default constructor (do not remove).
     */
    public TmOwnerdetailsEOImpl() {
    }


    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        if (mDefinitionObject == null) {
            mDefinitionObject = EntityDefImpl.findDefObject("oracle.tms.offencemanager.model.entity.TmOwnerdetailsEO");
        }
        return mDefinitionObject;
    }

    /**
     * Gets the attribute value for OwnerId, using the alias name OwnerId.
     * @return the OwnerId
     */
    public Number getOwnerId() {
        return (Number)getAttributeInternal(OWNERID);
    }

    /**
     * Sets <code>value</code> as the attribute value for OwnerId.
     * @param value value to set the OwnerId
     */
    public void setOwnerId(Number value) {
        setAttributeInternal(OWNERID, value);
    }

    /**
     * Gets the attribute value for Fname, using the alias name Fname.
     * @return the Fname
     */
    public String getFname() {
        return (String)getAttributeInternal(FNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for Fname.
     * @param value value to set the Fname
     */
    public void setFname(String value) {
        setAttributeInternal(FNAME, value);
    }

    /**
     * Gets the attribute value for Lname, using the alias name Lname.
     * @return the Lname
     */
    public String getLname() {
        return (String)getAttributeInternal(LNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for Lname.
     * @param value value to set the Lname
     */
    public void setLname(String value) {
        setAttributeInternal(LNAME, value);
    }

    /**
     * Gets the attribute value for Dateofbirth, using the alias name Dateofbirth.
     * @return the Dateofbirth
     */
    public Date getDateofbirth() {
        return (Date)getAttributeInternal(DATEOFBIRTH);
    }

    /**
     * Sets <code>value</code> as the attribute value for Dateofbirth.
     * @param value value to set the Dateofbirth
     */
    public void setDateofbirth(Date value) {
        setAttributeInternal(DATEOFBIRTH, value);
    }

    /**
     * Gets the attribute value for LandlineNo, using the alias name LandlineNo.
     * @return the LandlineNo
     */
    public String getLandlineNo() {
        return (String)getAttributeInternal(LANDLINENO);
    }

    /**
     * Sets <code>value</code> as the attribute value for LandlineNo.
     * @param value value to set the LandlineNo
     */
    public void setLandlineNo(String value) {
        setAttributeInternal(LANDLINENO, value);
    }

    /**
     * Gets the attribute value for MobileNo, using the alias name MobileNo.
     * @return the MobileNo
     */
    public String getMobileNo() {
        return (String)getAttributeInternal(MOBILENO);
    }

    /**
     * Sets <code>value</code> as the attribute value for MobileNo.
     * @param value value to set the MobileNo
     */
    public void setMobileNo(String value) {
        setAttributeInternal(MOBILENO, value);
    }

    /**
     * Gets the attribute value for Gender, using the alias name Gender.
     * @return the Gender
     */
    public String getGender() {
        return (String)getAttributeInternal(GENDER);
    }

    /**
     * Sets <code>value</code> as the attribute value for Gender.
     * @param value value to set the Gender
     */
    public void setGender(String value) {
        setAttributeInternal(GENDER, value);
    }

    /**
     * Gets the attribute value for TempAddr, using the alias name TempAddr.
     * @return the TempAddr
     */
    public String getTempAddr() {
        return (String)getAttributeInternal(TEMPADDR);
    }

    /**
     * Sets <code>value</code> as the attribute value for TempAddr.
     * @param value value to set the TempAddr
     */
    public void setTempAddr(String value) {
        setAttributeInternal(TEMPADDR, value);
    }

    /**
     * Gets the attribute value for PermAddr, using the alias name PermAddr.
     * @return the PermAddr
     */
    public String getPermAddr() {
        return (String)getAttributeInternal(PERMADDR);
    }

    /**
     * Sets <code>value</code> as the attribute value for PermAddr.
     * @param value value to set the PermAddr
     */
    public void setPermAddr(String value) {
        setAttributeInternal(PERMADDR, value);
    }

    /**
     * Gets the attribute value for Pincode, using the alias name Pincode.
     * @return the Pincode
     */
    public Number getPincode() {
        return (Number)getAttributeInternal(PINCODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for Pincode.
     * @param value value to set the Pincode
     */
    public void setPincode(Number value) {
        setAttributeInternal(PINCODE, value);
    }

    /**
     * Gets the attribute value for Occupation, using the alias name Occupation.
     * @return the Occupation
     */
    public String getOccupation() {
        return (String)getAttributeInternal(OCCUPATION);
    }

    /**
     * Sets <code>value</code> as the attribute value for Occupation.
     * @param value value to set the Occupation
     */
    public void setOccupation(String value) {
        setAttributeInternal(OCCUPATION, value);
    }

    /**
     * Gets the attribute value for PancardNo, using the alias name PancardNo.
     * @return the PancardNo
     */
    public String getPancardNo() {
        return (String)getAttributeInternal(PANCARDNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for PancardNo.
     * @param value value to set the PancardNo
     */
    public void setPancardNo(String value) {
        setAttributeInternal(PANCARDNO, value);
    }

    /**
     * Gets the attribute value for AddProofName, using the alias name AddProofName.
     * @return the AddProofName
     */
    public String getAddProofName() {
        return (String)getAttributeInternal(ADDPROOFNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for AddProofName.
     * @param value value to set the AddProofName
     */
    public void setAddProofName(String value) {
        setAttributeInternal(ADDPROOFNAME, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }

    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getTmVehicledetails() {
        return (RowIterator)getAttributeInternal(TMVEHICLEDETAILS);
    }

    /**
     * Gets the view accessor <code>RowSet</code> TmOffenceVVO1.
     */
    public RowSet getTmOffenceVVO1() {
        return (RowSet)getAttributeInternal(TMOFFENCEVVO1);
    }

    /**
     * @param ownerId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Number ownerId) {
        return new Key(new Object[]{ownerId});
    }


}
