package oracle.tms.offencemanager.model.appmodule;

import oracle.jbo.Key;
import oracle.jbo.Row;
import oracle.jbo.RowSetIterator;
import oracle.jbo.ViewCriteria;
import oracle.jbo.ViewCriteriaRow;
import oracle.jbo.ViewObject;
import oracle.jbo.domain.Number;
import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.ViewLinkImpl;

import oracle.jbo.server.ViewObjectImpl;
import oracle.jbo.server.ViewRowImpl;

import oracle.tms.offencemanager.model.appmodule.common.BrowseOffenceAM;
import oracle.tms.offencemanager.model.uiview.TmOffenceDetailsVOImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Jul 27 11:37:57 IST 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class BrowseOffenceAMImpl extends ApplicationModuleImpl implements BrowseOffenceAM {
    /**
     * This is the default constructor (do not remove).
     */
    public BrowseOffenceAMImpl() {
    }

    /**
     * Container's getter for TmOwnerdetails1.
     * @return TmOwnerdetails1
     */
    public ViewObjectImpl getTmOwnerdetails1() {
        return (ViewObjectImpl)findViewObject("TmOwnerdetails1");
    }

    /**
     * Container's getter for TmVehicledetails1.
     * @return TmVehicledetails1
     */
    public ViewObjectImpl getTmVehicledetails1() {
        return (ViewObjectImpl)findViewObject("TmVehicledetails1");
    }

    /**
     * Container's getter for TmOffenceDetails1.
     * @return TmOffenceDetails1
     */
    public TmOffenceDetailsVOImpl getTmOffenceDetails1() {
        return (TmOffenceDetailsVOImpl)findViewObject("TmOffenceDetails1");
    }


    /**
     * Container's getter for TmOwnerDetTmVehDetLink1.
     * @return TmOwnerDetTmVehDetLink1
     */
    public ViewLinkImpl getTmOwnerDetTmVehDetLink1() {
        return (ViewLinkImpl)findViewLink("TmOwnerDetTmVehDetLink1");
    }

    /**
     * Container's getter for TmVehDetTmOffenceDetLink1.
     * @return TmVehDetTmOffenceDetLink1
     */
    public ViewLinkImpl getTmVehDetTmOffenceDetLink1() {
        return (ViewLinkImpl)findViewLink("TmVehDetTmOffenceDetLink1");
    }
    
    public  void getOffenceDetails(Number key){
      ViewObjectImpl offenceVO = getQueryOffence1();
      offenceVO.setNamedWhereClauseParam("P_offence_id", key);
      offenceVO.executeQuery();
    }
    
    public void calculateTotal(){
        int num = 0;
      ViewObjectImpl offenceVO = getTmOffenceDetails1(); 
      RowSetIterator iterator = offenceVO.getRowSetIterator();
      
      while(iterator.hasNext() ){
        Row row = iterator.next();
        Number offenceId = (Number)row.getAttribute("OffenceId");
        System.out.println("Offenc ID: "+ offenceId ); 
        Key keyOffence = new Key(new Object[] { offenceId });

            // get the department based on the department identifier
            ViewRowImpl department = (ViewRowImpl)this.getTmOffence1().getRow(keyOffence);
      }
    }

    /**
     * Container's getter for TmOffence1.
     * @return TmOffence1
     */
    public ViewObjectImpl getTmOffence1() {
        return (ViewObjectImpl)findViewObject("TmOffence1");
    }

    /**
     * Container's getter for QueryOffence1.
     * @return QueryOffence1
     */
    public ViewObjectImpl getQueryOffence1() {
        return (ViewObjectImpl)findViewObject("QueryOffence1");
    }
}
